import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import Slider from "../components/slider";
import SaleItem from "../components/flashSalesItem";
import CategoryCard from "../components/categoryCardItem";
import FeaturedAndRatingMain from "../components/featuredAndRatingMain";
import ArrivalCard from "../components/arivalItem";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Slider />
      <SaleItem />
      <CategoryCard />
      <FeaturedAndRatingMain />
      <ArrivalCard />
    </div>
  );
}
