import Head from "next/head";
import Image from "next/image";
import Header from "../Components/Shared/Header";
import Slider from "../Components/Shared/Slider";
import SaleItem from "../Components/CardItems/FlashSalesItem";
import CategoryCard from "../Components/CardItems/CategoryCardItem";
import FeaturedAndRatingMain from "../Components/CardItems/FeaturedAndRatingMain";
import ArrivalCard from "../Components/CardItems/ArivalItem";
import DiscountCard from "../Components/CardItems/DiscountCardItem";
import CarsMain from "../Components/CardItems/CarsMain";
import PhonesMain from "../Components/CardItems/PhonesMain";
import Banner from "../Components/Shared/Banner";
import OpticsMain from "../Components/CardItems/OpticsMain";
import AllCategoryCard from "../Components/CardItems/AllCategoryCardItem";
import MoreData from "../Components/CardItems/MoreItem";
import ServiceCard from "../Components/Cards/ServiceCard";
import Footer from "../Components/Shared/Footer";
import BottomTab from "../Components/Shared/BottomNav";
import Modal from "../Components/Shared/Modal";
// import Dummy from "../components/carousel";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Slider />
      <SaleItem />
      <CategoryCard />
      <FeaturedAndRatingMain />
      <ArrivalCard />
      <DiscountCard />
      <CarsMain />
      <PhonesMain />
      <Banner />
      <OpticsMain />
      <AllCategoryCard />
      <MoreData />
      <ServiceCard />
      <Footer />
      {/* <Modal /> */}
      <BottomTab />
    </div>
  );
}
